apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "captcha.fullname" . }}
  labels:
    {{ include "captcha.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{ include "captcha.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{ include "captcha.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{ toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{ toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{ toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.service.grpc.port }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.http.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /live
              port: {{ .Values.service.http.port }}
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.grpc.port }}
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            {{ toYaml .Values.resources | nindent 12 }}
          env:
            - name: CAPTCHA_CONFIG_PATH
              value: /app/configs/config.yaml
          {{- if .Values.secret.cloudflareSecretKey }}
            - name: CAPTCHA_CLOUDFLARE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "captcha.fullname" . }}
                  key: cloudflare-secret-key
          {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/configs
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: {{ include "captcha.fullname" . }}
