apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "captcha.fullname" . }}
  labels:
    {{ include "captcha.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{ include "captcha.selectorLabels" . | nindent 6 }}
