{{- if .Values.secret.cloudflareSecretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "captcha.fullname" . }}
  labels:
    {{ include "captcha.labels" . | nindent 4 }}
type: Opaque
data:
  cloudflare-secret-key: {{ .Values.secret.cloudflareSecretKey | b64enc | quote }}
{{- end }}
