apiVersion: v1
kind: Service
metadata:
  name: {{ include "captcha.fullname" . }}
  labels:
    {{ include "captcha.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.grpc.port }}
      targetPort: {{ .Values.service.grpc.targetPort }}
      protocol: TCP
      name: grpc
  selector:
    {{ include "captcha.selectorLabels" . | nindent 4 }}
